public enum TokenType {
    IDENTIFIER,
    KEYWORD,
    SYMBOLS,
    SEPARATE_OPERATOR,
    ERROR,
    ARITHMETIC_OPERATOR,
    _STRING,
    INTEGER,
    DOUBLE,
    ASSIGNMENT_OPERATOR,
    EOF,
    BOOLEAN,
}
